name 'nginx_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures nginx_server'
long_description 'Installs/Configures nginx_server'
version '0.1.0'
chef_version '>= 14.0'
